### ISSUE TITLE
Ruby version 2.3.4 when 2.3.3 is installed

### ISSUE THREAD

**Issue by osteffich** [wvuweb/hammer#53]
There is an issue when you run `vagrant up`  the incorrect version of ruby is installed.

**Comment by zeroedin** [comment]
This is due to ubuntu apt-get package manager being bumped to ruby version `2.3.4` for packages `ruby2.3` and  `ruby2.3-dev` an alternative way to install ruby such as using [chruby](https://github.com/postmodern/chruby) as an option to remedy the dependency chain update.  I can  also just upgrade hammer to use newer version, I'll have to see which is the better option.  I will release a patch tomorrow that will fix this issue.  However, this may be a breaking change and might cause everyone to have to destroy and rebuild their vagrant boxes on their next hammer update as the gemfile for hammer would change version.

**Comment by zeroedin** [comment]
Issue was fixed in wvuweb/hammer-vm@6e824dd9ffc2b1650b3682448925149a291df596.  It will only take effect if someone chooses to rebuild their hammer-vm install.  Otherwise if their current build is working they shouldn't have an issue upgrading hammer.
